Turn off Travis notification to Slack
thefrontside/folio-ui-eholdings-deploy pull request #8
Opened 2018-01-17 22:23 UTC by cherewaty

The Travis notifications to Slack intercepted by bitbot need refactoring, since they're showing the latest commit from this repo instead of `ui-eholdings`. This turns them off until we can revisit bitbot.

2018-01-17 22:44 UTC, cowboyd approved these changes

2018-01-17 22:44 UTC, cowboyd requested changes
Actually, let's just go ahead and delete them. No sense in dead Travis config

2018-01-17 23:13 UTC, cherewaty commented
Now deleted instead of commenting out.

2018-01-18 04:49 UTC, cowboyd approved these changes

2018-01-18 04:49 UTC, cowboyd approved these changes

2018-01-18 12:09 UTC, merged